sgd2016-dev-postgresql:
  container_name: sgd2016-dev-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/sgd2016/dev-postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=sgd2016
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
