sgd2016-elasticsearch:
  container_name: sgd2016-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/sgd2016/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
sgd2016-postgresql:
  container_name: sgd2016-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/sgd2016/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=sgd2016
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
